services:
  web:
    build:
      context: ./dockerfiles
      dockerfile: local.dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/src
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Password1234!
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: arst@arst.se
      PGADMIN_DEFAULT_PASSWORD: arst
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"

volumes:
  db-data:
