services:
  web:
    build:
      context: ./dockerfiles
      dockerfile: local.dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/src
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Password1234!
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data:
